### ISSUE TITLE
Wrong URL in code

### ISSUE THREAD

**Issue by ericorain** [nornir-automation/nornir.tech.src#11]
The following URL is wrong for Netmiko in the file "nornir.tech.src/data/nornir/plugins.yaml":
###################
    - url: https://github.com/nornir-automation/napalm_nornir
      name: nornir_netmiko
      maintainer: "[ktbyers](https://github.com/ktbyers)"
      plugin_types:
###################

**Comment by dbarrosop** [comment]
Thanks for reporting, next time feel free to send a PR directly if you feel like it!
