### ISSUE TITLE
Support page is pointing users to discourse instead of Github discussions

### ISSUE THREAD

**Issue by writememe** [nornir-automation/nornir.tech.src#21]
The [support page](https://github.com/nornir-automation/nornir.tech.src/blob/master/content/support.md#community-support) refers to nornir discourse, but I believe that this support channel has been retired.

I'm assuming we would want to change it to [Github discussions](https://github.com/nornir-automation/nornir/discussions) so I will raise a PR and reference this issue.

**Comment by dbarrosop** [comment]
You are right, that needs to be fixed
